ICMP_PROTO = 1
TCP_PROTO = 6
UDP_PROTO = 17

ETHERNET_HEADER_LENGTH = 14
IP_HEADER_LENGTH = 20
ICMP_HEADER_LENGTH = 8
UDP_HEADER_LENGTH = 8
TCP_HEADER_LENGTH = 20

# The inner_ip.tos should be 92=0x5c=01011100, because the INT_IPv4_DSCP=0x17(6 bit, 00010111)
INT_IPv4_DSCP = 0x66

INT_REPORT_HEADER_LENGTH = 16
INT_SHIM_LENGTH = 4
INT_SHIM_WORD_LENGTH = 1
INT_META_LENGTH = 8
INT_META_WORD_LENGTH = 2

OUTER_ETHERNET_OFFSET = 0
OUTER_IP_HEADER = OUTER_ETHERNET_OFFSET + ETHERNET_HEADER_LENGTH
OUTER_L4_HEADER_OFFSET = OUTER_IP_HEADER + IP_HEADER_LENGTH

INNER_ETHERNET_OFFSET = INT_REPORT_HEADER_LENGTH
INNER_IP_HEADER_OFFSET = INNER_ETHERNET_OFFSET + ETHERNET_HEADER_LENGTH
INNER_L4_HEADER_OFFSET = INNER_IP_HEADER_OFFSET + IP_HEADER_LENGTH

INT_SHIM_OFFSET = INT_REPORT_HEADER_LENGTH + ETHERNET_HEADER_LENGTH + IP_HEADER_LENGTH
